# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(LDAP_URL): ldap://localhost
    env(LDAP_DOMAIN_BASE):
    env(LDAP_DOMAIN_FILTER): (&(associatedDomain=%s)(objectClass=organizationalUnit))
    env(LDAP_DOMAIN_ATTRIBUTE): associatedDomain
    env(LDAP_USER_BASE):
    env(LDAP_USER_FILTER): (&(mail=%s)(objectClass=person))
    env(LDAP_USER_NAME_ATTRIBUTE): mail
    env(LDAP_USER_DN_ATTRIBUTE): cn
    env(DATABASE_DRIVER): pdo_mysql
    env(DATABASE_URL):
    env(DATABASE_DOMAIN_QUERY):
    env(DATABASE_USER_QUERY):
    env(DATABASE_USER_NAME_FIELD): email
    env(DATABASE_USER_DN_FIELD): name
    env(IMAP_SERVERS): '["imap://imap.%env(PROVIDER_DOMAIN)%/tls"]'
    env(SMTP_SERVERS): '["smtp://smtp.%env(PROVIDER_DOMAIN)%:587/tls"]'
    env(POP3_SERVERS): '[]'
    env(ACTIVESYNC_URL):
    env(PROVIDER_NAME):
    env(PROVIDER_DOMAIN):
    env(PROVIDER_SHORT_NAME):

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $logRequests: '%log_requests%'
            $logResponses: '%log_responses%'

    # makes classes in AutodiscoverXml/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AutodiscoverXml\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    AutodiscoverXml\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    AutodiscoverXml\Connection\LdapConnection:
        arguments:
            $url: '%env(string:LDAP_URL)%'

    AutodiscoverXml\Provider\DomainProvider:
        arguments: [!tagged app.domain_provider]

    AutodiscoverXml\Provider\LdapDomainProvider:
        tags: ['app.domain_provider']
        arguments:
            $base: '%env(string:LDAP_DOMAIN_BASE)%'
            $filter: '%env(string:LDAP_DOMAIN_FILTER)%'
            $attribute: '%env(string:LDAP_DOMAIN_ATTRIBUTE)%'

    AutodiscoverXml\Provider\DoctrineDomainProvider:
        tags: ['app.domain_provider']
        arguments:
            $query: '%env(string:DATABASE_DOMAIN_QUERY)%'

    AutodiscoverXml\Provider\UserProvider:
        arguments: [!tagged app.username_provider]

    AutodiscoverXml\Provider\LdapUserProvider:
        tags: ['app.username_provider']
        arguments:
            $base: '%env(string:LDAP_USER_BASE)%'
            $filter: '%env(string:LDAP_USER_FILTER)%'
            $userNameAttribute: '%env(string:LDAP_USER_NAME_ATTRIBUTE)%'
            $displayNameAttribute: '%env(string:LDAP_USER_DN_ATTRIBUTE)%'

    AutodiscoverXml\Provider\DoctrineUserProvider:
        tags: ['app.username_provider']
        arguments:
            $query: '%env(string:DATABASE_USER_QUERY)%'
            $userNameField: '%env(string:DATABASE_USER_NAME_FIELD)%'
            $displayNameField: '%env(string:DATABASE_USER_DN_FIELD)%'

    AutodiscoverXml\Provider\ServiceProvider:
        arguments:
            $imaps: '%env(json:IMAP_SERVERS)%'
            $smtps: '%env(json:SMTP_SERVERS)%'
            $pop3s: '%env(json:POP3_SERVERS)%'
            $activesync: '%env(ACTIVESYNC_URL)%'
            $providerName: '%env(string:PROVIDER_NAME)%'
            $providerDomain: '%env(string:PROVIDER_DOMAIN)%'
            $providerShortName: '%env(string:PROVIDER_SHORT_NAME)%'
